# Generated by Django 4.0.6 on 2024-01-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0003_carmodel_profilemodel_servicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('CarId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_no', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('new_state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('deal_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_available', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('repo_date', models.DateField()),
                ('segment', models.CharField(max_length=100)),
                ('parked_at', models.TextField()),
                ('yard_city', models.CharField(max_length=100)),
                ('valuation_amount', models.FloatField()),
                ('valuation_report_link', models.URLField(max_length=500)),
                ('manufacturing_year', models.IntegerField()),
                ('base_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=15)),
                ('CD', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('RegisteredId', models.CharField(blank=True, max_length=255, null=True)),
                ('PaymentDetails', models.CharField(max_length=255)),
                ('InterestedIn', models.CharField(max_length=255)),
                ('RenewalFee', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Auction_type',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='User_id',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='experyDate',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='format',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='hightestBiddingPrice',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='img',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='location',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rc_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='vehicleNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='Car_details',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='myApi.carmodel'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='aadhar',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='panCard',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApi.item')),
            ],
        ),
    ]
