# Generated by Django 5.0 on 2024-01-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0004_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='rc_available',
            field=models.BooleanField(default=False),
        ),
    ]
