# Generated by Django 4.0.6 on 2024-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0005_requestforregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
        ),
    ]
