# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0005_carmodel_rc_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('CarId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='aadhar',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='panCard',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
