# Generated by Django 4.0.6 on 2024-01-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0006_mydatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.CharField(max_length=255)),
                ('deal_no', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('dealer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('new_state', models.CharField(max_length=255)),
                ('deal_date', models.DateField()),
                ('segment', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=255)),
                ('mfg_year', models.IntegerField()),
                ('engine_no', models.CharField(max_length=255)),
                ('chassis_no', models.CharField(max_length=255)),
                ('repo_date', models.DateField()),
                ('vehicle_parked_with', models.CharField(max_length=255)),
                ('yard_name', models.CharField(max_length=255)),
                ('parked_at', models.CharField(max_length=255)),
                ('yard_city', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
