# Generated by Django 4.2.9 on 2024-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0009_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Image',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
