# Generated by Django 5.0.1 on 2024-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreigster',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Driver'), (3, 'User')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='accountreigster',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
